
/**
 * IalMes.h
 * IalMes Interface Module Definition
 */

#ifndef _IALMES_H_
#define _IALMES_H_

#include "Hal/HalAi.h"
#include "Hal/HalFComm.h"
#include "Hal/HalVme.h"

#include "Ial/IalHmi.h"
#include "IalRtds.h"

/** @name Symbolic Constants
 * Symbolic Constants
 */
///@{

// Control Input, Output 은 채널별로 인덱스가 정의되어 있다.
// 기본 정의에 맞게 Idx를 정의하여야 한다.
// 0          ~ 15         : Analog Input
// 16         ~ 15 + 200*1 : FComm #1
// 16 + 200*1 ~ 15 + 200*2 : FComm #1
// 16 + 200*2 ~ 15 + 200*3 : FComm #1
// 16 + 200*3 ~ 15 + 200*4 : FComm #1


//	#define IALMES_FCOMM_DUMMY_SIZE		5

#define IALMES_HIGH_SPEED			0x0
#define IALMES_LOW_SPEED			0x1

// Header 포함(Header 크기4)
#define IALMES_HIGH_SPEED_FRAMESIZE			20
#define IALMES_LOW_SPEED_FRAMESIZE			128

#define IALMES_ID_START			0x0
#define IALMES_ID_MAX			0x5

#define IALMES_AI_START				0										// to MES with only HDR
#define IALMES_FCOMM_CH1_START		HALAI_CH_NUM										// to MES with only HDR
#define IALMES_FCOMM_CH2_START		(IALMES_FCOMM_CH1_START)		// to MESU A with small Data
#define IALMES_FCOMM_CH3_START		(IALMES_FCOMM_CH2_START)		// to MESU B with small Data
#define IALMES_FCOMM_CH4_START		(IALMES_FCOMM_CH3_START)		// to MESU C with small Data

// Hmi In/Out Data : HmiApp 과 연결해야 함.
#define IALMES_HMI_START			(IALMES_FCOMM_CH4_START + IALRTDS_FCOMM_SIZE)		// to MESU C with small Data


/** @name Symbolic Constants
 * Symbolic Constants
 */
///@{

/****************************************************************************/
/* MES Analog I/O Idx 정의                                        */
/****************************************************************************/
///> MES01 Analog Input IDX
#define IALMES01_AI_IASY_IDX		0
#define IALMES01_AI_IBSY_IDX		1
#define IALMES01_AI_ICSY_IDX		2
#define IALMES01_AI_IASD_IDX		3
#define IALMES01_AI_IBSD_IDX		4
#define IALMES01_AI_ICSD_IDX		5

#define IALMES01_AI_IASS_IDX		6
#define IALMES01_AI_IBSS_IDX		7
#define IALMES01_AI_ICSS_IDX		8
#define IALMES01_AI_IG_IDX			9

#define IALMES01_AI_IAP_IDX			10
#define IALMES01_AI_IBP_IDX			11
#define IALMES01_AI_ICP_IDX			12
#define IALMES01_AI_IAN_IDX			13
#define IALMES01_AI_IBN_IDX			14
#define IALMES01_AI_ICN_IDX			15

///> MES02 Analog Input IDX
#define IALMES02_AI_UASY_IDX		0
#define IALMES02_AI_UBSY_IDX		1
#define IALMES02_AI_UCSY_IDX		2
#define IALMES02_AI_UNSY_IDX		3
#define IALMES02_AI_UASD_IDX		4
#define IALMES02_AI_UBSD_IDX		5
#define IALMES02_AI_UCSD_IDX		6
#define IALMES02_AI_UNSD_IDX		7

#define IALMES02_AI_IDCP_IDX		8
#define IALMES02_AI_IDCN_IDX		9
#define IALMES02_AI_IDCPO_IDX		10
#define IALMES02_AI_IDCBO_IDX		11

#define IALMES02_AI_UDCP_IDX		12
#define IALMES02_AI_UDCN_IDX		13
#define IALMES02_AI_UDCPO_IDX		14
#define IALMES02_AI_UDCBO_IDX		15


/****************************************************************************/
/* MES 의 송신 데이터로 수신부에서는 아래의 Idx를 사용해야 한다.            */
/****************************************************************************/

///> MES 수신 데이터는 IalMes.h 의 정의를 사용한다


///> CCS FComm Tx IDX to MES
#define IALMES_FCOMM_STARTCODE_IDX	IALMES_FCOMM_CH1_START
#define IALMES_FCOMM_CRC_IDX		(IALMES_FCOMM_CH1_START + 1)
#define IALMES_FCOMM_SEQNUM_IDX		(IALMES_FCOMM_CH1_START + 2)	// Length + SequenceNumber
#define IALMES_FCOMM_LEN_IDX		(IALMES_FCOMM_CH1_START + 3)	// Length + SequenceNumber

// RAW Value
#define IALMES_FCOMM_IASY_IDX		(IALMES_FCOMM_CH1_START + 4)
#define IALMES_FCOMM_IBSY_IDX		(IALMES_FCOMM_CH1_START + 5)
#define IALMES_FCOMM_ICSY_IDX		(IALMES_FCOMM_CH1_START + 6)
#define IALMES_FCOMM_IASD_IDX		(IALMES_FCOMM_CH1_START + 7)
#define IALMES_FCOMM_IBSD_IDX		(IALMES_FCOMM_CH1_START + 8)
#define IALMES_FCOMM_ICSD_IDX		(IALMES_FCOMM_CH1_START + 9)

#define IALMES_FCOMM_IASS_IDX		(IALMES_FCOMM_CH1_START + 10)
#define IALMES_FCOMM_IBSS_IDX		(IALMES_FCOMM_CH1_START + 11)
#define IALMES_FCOMM_ICSS_IDX		(IALMES_FCOMM_CH1_START + 12)
#define IALMES_FCOMM_IG_IDX			(IALMES_FCOMM_CH1_START + 13)

#define IALMES_FCOMM_IAP_IDX		(IALMES_FCOMM_CH1_START + 14)
#define IALMES_FCOMM_IBP_IDX		(IALMES_FCOMM_CH1_START + 15)
#define IALMES_FCOMM_ICP_IDX		(IALMES_FCOMM_CH1_START + 16)
#define IALMES_FCOMM_IAN_IDX		(IALMES_FCOMM_CH1_START + 17)
#define IALMES_FCOMM_IBN_IDX		(IALMES_FCOMM_CH1_START + 18)
#define IALMES_FCOMM_ICN_IDX		(IALMES_FCOMM_CH1_START + 19)

#define IALMES_FCOMM_UASY_IDX		(IALMES_FCOMM_CH1_START + 20)
#define IALMES_FCOMM_UBSY_IDX		(IALMES_FCOMM_CH1_START + 21)
#define IALMES_FCOMM_UCSY_IDX		(IALMES_FCOMM_CH1_START + 22)
#define IALMES_FCOMM_UNSY_IDX		(IALMES_FCOMM_CH1_START + 23)
#define IALMES_FCOMM_UASD_IDX		(IALMES_FCOMM_CH1_START + 24)
#define IALMES_FCOMM_UBSD_IDX		(IALMES_FCOMM_CH1_START + 25)
#define IALMES_FCOMM_UCSD_IDX		(IALMES_FCOMM_CH1_START + 26)
#define IALMES_FCOMM_UNSD_IDX		(IALMES_FCOMM_CH1_START + 27)

#define IALMES_FCOMM_IDCP_IDX		(IALMES_FCOMM_CH1_START + 28)
#define IALMES_FCOMM_IDCN_IDX		(IALMES_FCOMM_CH1_START + 29)
#define IALMES_FCOMM_IDCPO_IDX		(IALMES_FCOMM_CH1_START + 30)
#define IALMES_FCOMM_IDCBO_IDX		(IALMES_FCOMM_CH1_START + 31)

#define IALMES_FCOMM_UDCP_IDX		(IALMES_FCOMM_CH1_START + 32)
#define IALMES_FCOMM_UDCN_IDX		(IALMES_FCOMM_CH1_START + 33)
#define IALMES_FCOMM_UDCPO_IDX		(IALMES_FCOMM_CH1_START + 34)
#define IALMES_FCOMM_UDCBO_IDX		(IALMES_FCOMM_CH1_START + 35)

// RMS
#define IALMES_FCOMM_IASYRMS_IDX		(IALMES_FCOMM_CH1_START + 36)
#define IALMES_FCOMM_IBSYRMS_IDX		(IALMES_FCOMM_CH1_START + 37)
#define IALMES_FCOMM_ICSYRMS_IDX		(IALMES_FCOMM_CH1_START + 38)
#define IALMES_FCOMM_IASDRMS_IDX		(IALMES_FCOMM_CH1_START + 39)
#define IALMES_FCOMM_IBSDRMS_IDX		(IALMES_FCOMM_CH1_START + 40)
#define IALMES_FCOMM_ICSDRMS_IDX		(IALMES_FCOMM_CH1_START + 41)

#define IALMES_FCOMM_IASSRMS_IDX		(IALMES_FCOMM_CH1_START + 42)
#define IALMES_FCOMM_IBSSRMS_IDX		(IALMES_FCOMM_CH1_START + 43)
#define IALMES_FCOMM_ICSSRMS_IDX		(IALMES_FCOMM_CH1_START + 44)
#define IALMES_FCOMM_IGRMS_IDX		(IALMES_FCOMM_CH1_START + 	45)

#define IALMES_FCOMM_IAPRMS_IDX		(IALMES_FCOMM_CH1_START + 	46)
#define IALMES_FCOMM_IBPRMS_IDX		(IALMES_FCOMM_CH1_START + 	47)
#define IALMES_FCOMM_ICPRMS_IDX		(IALMES_FCOMM_CH1_START + 	48)
#define IALMES_FCOMM_IANRMS_IDX		(IALMES_FCOMM_CH1_START + 	49)
#define IALMES_FCOMM_IBNRMS_IDX		(IALMES_FCOMM_CH1_START + 	50)
#define IALMES_FCOMM_ICNRMS_IDX		(IALMES_FCOMM_CH1_START + 	51)

#define IALMES_FCOMM_UASYRMS_IDX		(IALMES_FCOMM_CH1_START + 52)
#define IALMES_FCOMM_UBSYRMS_IDX		(IALMES_FCOMM_CH1_START + 53)
#define IALMES_FCOMM_UCSYRMS_IDX		(IALMES_FCOMM_CH1_START + 54)
#define IALMES_FCOMM_UNSYRMS_IDX		(IALMES_FCOMM_CH1_START + 55)
#define IALMES_FCOMM_UASDRMS_IDX		(IALMES_FCOMM_CH1_START + 56)
#define IALMES_FCOMM_UBSDRMS_IDX		(IALMES_FCOMM_CH1_START + 57)
#define IALMES_FCOMM_UCSDRMS_IDX		(IALMES_FCOMM_CH1_START + 58)
#define IALMES_FCOMM_UNSDRMS_IDX		(IALMES_FCOMM_CH1_START + 59)

#define IALMES_FCOMM_IDCPRMS_IDX		(IALMES_FCOMM_CH1_START + 60)
#define IALMES_FCOMM_IDCNRMS_IDX		(IALMES_FCOMM_CH1_START + 61)
#define IALMES_FCOMM_IDCPORMS_IDX		(IALMES_FCOMM_CH1_START + 62)
#define IALMES_FCOMM_IDCBORMS_IDX		(IALMES_FCOMM_CH1_START + 63)

#define IALMES_FCOMM_UDCPRMS_IDX		(IALMES_FCOMM_CH1_START + 64)
#define IALMES_FCOMM_UDCNRMS_IDX		(IALMES_FCOMM_CH1_START + 65)
#define IALMES_FCOMM_UDCPORMS_IDX		(IALMES_FCOMM_CH1_START + 66)
#define IALMES_FCOMM_UDCBORMS_IDX		(IALMES_FCOMM_CH1_START + 67)

// LPF
#define IALMES_FCOMM_IASYLP_IDX		(IALMES_FCOMM_CH1_START + 68)
#define IALMES_FCOMM_IBSYLP_IDX		(IALMES_FCOMM_CH1_START + 69)
#define IALMES_FCOMM_ICSYLP_IDX		(IALMES_FCOMM_CH1_START + 70)
#define IALMES_FCOMM_IASDLP_IDX		(IALMES_FCOMM_CH1_START + 71)
#define IALMES_FCOMM_IBSDLP_IDX		(IALMES_FCOMM_CH1_START + 72)
#define IALMES_FCOMM_ICSDLP_IDX		(IALMES_FCOMM_CH1_START + 73)

#define IALMES_FCOMM_IASSLP_IDX		(IALMES_FCOMM_CH1_START + 74)
#define IALMES_FCOMM_IBSSLP_IDX		(IALMES_FCOMM_CH1_START + 75)
#define IALMES_FCOMM_ICSSLP_IDX		(IALMES_FCOMM_CH1_START + 76)
#define IALMES_FCOMM_IGLP_IDX		(IALMES_FCOMM_CH1_START + 77)

#define IALMES_FCOMM_IAPLP_IDX		(IALMES_FCOMM_CH1_START + 78)
#define IALMES_FCOMM_IBPLP_IDX		(IALMES_FCOMM_CH1_START + 79)
#define IALMES_FCOMM_ICPLP_IDX		(IALMES_FCOMM_CH1_START + 80)
#define IALMES_FCOMM_IANLP_IDX		(IALMES_FCOMM_CH1_START + 81)
#define IALMES_FCOMM_IBNLP_IDX		(IALMES_FCOMM_CH1_START + 82)
#define IALMES_FCOMM_ICNLP_IDX		(IALMES_FCOMM_CH1_START + 83)

#define IALMES_FCOMM_UASYLP_IDX		(IALMES_FCOMM_CH1_START + 84)
#define IALMES_FCOMM_UBSYLP_IDX		(IALMES_FCOMM_CH1_START + 85)
#define IALMES_FCOMM_UCSYLP_IDX		(IALMES_FCOMM_CH1_START + 86)
#define IALMES_FCOMM_UNSYLP_IDX		(IALMES_FCOMM_CH1_START + 87)
#define IALMES_FCOMM_UASDLP_IDX		(IALMES_FCOMM_CH1_START + 88)
#define IALMES_FCOMM_UBSDLP_IDX		(IALMES_FCOMM_CH1_START + 89)
#define IALMES_FCOMM_UCSDLP_IDX		(IALMES_FCOMM_CH1_START + 90)
#define IALMES_FCOMM_UNSDLP_IDX		(IALMES_FCOMM_CH1_START + 91)

#define IALMES_FCOMM_IDCPLP_IDX		(IALMES_FCOMM_CH1_START + 92)
#define IALMES_FCOMM_IDCNLP_IDX		(IALMES_FCOMM_CH1_START + 93)
#define IALMES_FCOMM_IDCPOLP_IDX	(IALMES_FCOMM_CH1_START + 94)
#define IALMES_FCOMM_IDCBOLP_IDX	(IALMES_FCOMM_CH1_START + 95)

#define IALMES_FCOMM_UDCPLP_IDX		(IALMES_FCOMM_CH1_START + 96)
#define IALMES_FCOMM_UDCNLP_IDX		(IALMES_FCOMM_CH1_START + 97)
#define IALMES_FCOMM_UDCPOLP_IDX	(IALMES_FCOMM_CH1_START + 98)
#define IALMES_FCOMM_UDCBOLP_IDX	(IALMES_FCOMM_CH1_START + 99)



#define IALMES_FCOMM_LAST_IDX		(IALMES_FCOMM_UDCBOLP_IDX)
#define IALMES_FCOMM_SIZE			(128) //(IALMES_FCOMM_LAST_IDX -IALMES_FCOMM_STARTCODE_IDX + 1)


typedef struct stAiDatatype {
	U_IALDATA_TYPE	Ch1;						// 1	- 1
	U_IALDATA_TYPE	Ch2;						// 2	- 1
	U_IALDATA_TYPE	Ch3;						// 3	- 1
	U_IALDATA_TYPE	Ch4;						// 4	- 1
	U_IALDATA_TYPE	Ch5;						// 5	- 1
	U_IALDATA_TYPE	Ch6;						// 6	- 1
	U_IALDATA_TYPE	Ch7;						// 7	- 1
	U_IALDATA_TYPE	Ch8;						// 8	- 1
	U_IALDATA_TYPE	Ch9;						// 9	- 1
	U_IALDATA_TYPE	Ch10;						// 10	- 1
	U_IALDATA_TYPE	Ch11;						// 11	- 1
	U_IALDATA_TYPE	Ch12;						// 12	- 1
	U_IALDATA_TYPE	Ch13;						// 13	- 1
	U_IALDATA_TYPE	Ch14;						// 14	- 1
	U_IALDATA_TYPE	Ch15;						// 15	- 1
	U_IALDATA_TYPE	Ch16;						// 16	- 1
} ST_AIDATA_TYPE;


typedef struct stMesLowSpeedTxtype {
	U_IALDATA_TYPE	uHeader[PROTOCOL_HEADER_LEN];	// 0~3

	U_IALDATA_TYPE	Ia_tr_pri;						// 4	- 1
	U_IALDATA_TYPE	Ib_tr_pri;						// 5	- 2

	U_IALDATA_TYPE	Ic_tr_pri;
	U_IALDATA_TYPE	Iab_tr_sec;
	U_IALDATA_TYPE	Ibc_tr_sec;
	U_IALDATA_TYPE	Ica_tr_sec;
	U_IALDATA_TYPE	Va_tr_pri;			// 10	- 7
	
	U_IALDATA_TYPE	Vb_tr_pri;
	U_IALDATA_TYPE	Vc_tr_pri;
	U_IALDATA_TYPE	Va_tr_sec;
	U_IALDATA_TYPE	Vb_tr_sec;
	U_IALDATA_TYPE	Vc_tr_sec;			// 15	- 12
	
	U_IALDATA_TYPE	Ia_t;
	U_IALDATA_TYPE	Ib_t;
	U_IALDATA_TYPE	Ic_t;
	U_IALDATA_TYPE	Ia_P;
	U_IALDATA_TYPE	Ib_P;				// 20	- 17
	
	U_IALDATA_TYPE	Ic_P;
	U_IALDATA_TYPE	Ia_N;
	U_IALDATA_TYPE	Ib_N;
	U_IALDATA_TYPE	Ic_N;
	U_IALDATA_TYPE	Idc_P;				// 25	- 22
	
	U_IALDATA_TYPE	Idc_N;
	U_IALDATA_TYPE	Vdc_P;
	U_IALDATA_TYPE	Vdc_N;
	U_IALDATA_TYPE	Ig;
	U_IALDATA_TYPE	Vmag_pseq;			// 30	- 27
	
	U_IALDATA_TYPE	Vmag_nseq;
	U_IALDATA_TYPE	Vmag_lpf;
	U_IALDATA_TYPE	Theta;
	U_IALDATA_TYPE	Freq;
	U_IALDATA_TYPE	Va_rms;				// 35	- 32
	
	U_IALDATA_TYPE	Vb_rms;
	U_IALDATA_TYPE	Vc_rms;
	U_IALDATA_TYPE	Va_tr_pri_lpf;
	U_IALDATA_TYPE	Vb_tr_pri_lpf;
	U_IALDATA_TYPE	Vc_tr_pri_lpf;		// 40	- 37
	
	U_IALDATA_TYPE	Ia_t_lpf;
	U_IALDATA_TYPE	Ib_t_lpf;
	U_IALDATA_TYPE	Ic_t_lpf;
	U_IALDATA_TYPE	Ia_t_hpf;
	U_IALDATA_TYPE	Ib_t_hpf;			// 45	- 42
	
	U_IALDATA_TYPE	Ic_t_hpf;
	U_IALDATA_TYPE	Imag_pseq;
	U_IALDATA_TYPE	Imag_nseq;
	U_IALDATA_TYPE	Imag_t_lpf;
	U_IALDATA_TYPE	Iab_tr_sec_lpf;		// 50	- 47
	
	U_IALDATA_TYPE	Ibc_tr_sec_lpf;
	U_IALDATA_TYPE	Ica_tr_sec_lpf;
	U_IALDATA_TYPE	Imag_tr_sec_pseq;
	U_IALDATA_TYPE	Imag_tr_sec_nseq;
	U_IALDATA_TYPE	Imag_tr_sec_lpf;	// 55	- 52
	
	U_IALDATA_TYPE	Imag_tr_sec_hpf;
	U_IALDATA_TYPE	Ppcc;
	U_IALDATA_TYPE	Qpcc;
	U_IALDATA_TYPE	Ia_P_lpf;
	U_IALDATA_TYPE	Ib_P_lpf;			// 60	- 57
	
	U_IALDATA_TYPE	Ic_P_lpf;
	U_IALDATA_TYPE	Ia_N_lpf;
	U_IALDATA_TYPE	Ib_N_lpf;
	U_IALDATA_TYPE	Ic_N_lpf;
	U_IALDATA_TYPE	Ia_t_rms;			// 65	- 62
	
	U_IALDATA_TYPE	Ib_t_rms;
	U_IALDATA_TYPE	Ic_t_rms;
	U_IALDATA_TYPE	Ig_lpf;
	U_IALDATA_TYPE	Idc_P_lpf;
	U_IALDATA_TYPE	Idc_N_lpf;			// 70	- 67
	
	U_IALDATA_TYPE	Idc_P_hpf;
	U_IALDATA_TYPE	Idc_N_hpf;
	U_IALDATA_TYPE	Ia_P_rms;
	U_IALDATA_TYPE	Ib_P_rms;
	U_IALDATA_TYPE	Ic_P_rms;			// 75	- 72
	
	U_IALDATA_TYPE	Ia_N_rms;
	U_IALDATA_TYPE	Ib_N_rms;
	U_IALDATA_TYPE	Ic_N_rms;
	U_IALDATA_TYPE	Pdc;
	U_IALDATA_TYPE	Pac;				// 80	- 77
	U_IALDATA_TYPE	Status;				// 81	- 78

 } ST_MESTX_LS_TYPE;

typedef ST_MESTX_LS_TYPE	ST_MESRX_LS_TYPE;

typedef struct stMesHighSpeedTxtype {
	U_IALDATA_TYPE	uHeader[PROTOCOL_HEADER_LEN];	// 0~3

	U_IALDATA_TYPE	Ia_t;
	U_IALDATA_TYPE	Ib_t;
	U_IALDATA_TYPE	Ic_t;
	U_IALDATA_TYPE	Ia_P;
	U_IALDATA_TYPE	Ib_P;				// 8	- 5
	
	U_IALDATA_TYPE	Ic_P;
	U_IALDATA_TYPE	Ia_N;
	U_IALDATA_TYPE	Ib_N;
	U_IALDATA_TYPE	Ic_N;
	U_IALDATA_TYPE	Idc_P;				// 13	- 10
	
	U_IALDATA_TYPE	Idc_N;
	U_IALDATA_TYPE	Vdc_P;
	U_IALDATA_TYPE	Vdc_N;
	U_IALDATA_TYPE	Ig;

 } ST_MESTX_HS_TYPE;

typedef struct stMesCpuTxtype {
// 	U_IALDATA_TYPE	Vmag_pseq;		
	
//	U_IALDATA_TYPE	Vmag_nseq;
//	U_IALDATA_TYPE	Vmag_lpf;
//	U_IALDATA_TYPE	Theta;
	U_IALDATA_TYPE	Freq;
	U_IALDATA_TYPE	Va_rms;			
	
	U_IALDATA_TYPE	Vb_rms;
	U_IALDATA_TYPE	Vc_rms;
	U_IALDATA_TYPE	Va_tr_pri_lpf;
	U_IALDATA_TYPE	Vb_tr_pri_lpf;
	U_IALDATA_TYPE	Vc_tr_pri_lpf;	
	
	U_IALDATA_TYPE	Ia_t_lpf;
	U_IALDATA_TYPE	Ib_t_lpf;
	U_IALDATA_TYPE	Ic_t_lpf;
	U_IALDATA_TYPE	Ia_t_hpf;
	U_IALDATA_TYPE	Ib_t_hpf;		
	
	U_IALDATA_TYPE	Ic_t_hpf;
	U_IALDATA_TYPE	Imag_pseq;
	U_IALDATA_TYPE	Imag_nseq;
	U_IALDATA_TYPE	Imag_t_lpf;
	U_IALDATA_TYPE	Iab_tr_sec_lpf;	
	
	U_IALDATA_TYPE	Ibc_tr_sec_lpf;
	U_IALDATA_TYPE	Ica_tr_sec_lpf;
	U_IALDATA_TYPE	Imag_tr_sec_pseq;
	U_IALDATA_TYPE	Imag_tr_sec_nseq;
	U_IALDATA_TYPE	Imag_tr_sec_lpf;
	
	U_IALDATA_TYPE	Imag_tr_sec_hpf;
	U_IALDATA_TYPE	Ppcc;
	U_IALDATA_TYPE	Qpcc;
	U_IALDATA_TYPE	Ia_P_lpf;
	U_IALDATA_TYPE	Ib_P_lpf;		
	
	U_IALDATA_TYPE	Ic_P_lpf;
	U_IALDATA_TYPE	Ia_N_lpf;
	U_IALDATA_TYPE	Ib_N_lpf;
	U_IALDATA_TYPE	Ic_N_lpf;
	U_IALDATA_TYPE	Ia_t_rms;		
	
	U_IALDATA_TYPE	Ib_t_rms;
	U_IALDATA_TYPE	Ic_t_rms;
	U_IALDATA_TYPE	Ig_lpf;
	U_IALDATA_TYPE	Idc_P_lpf;
	U_IALDATA_TYPE	Idc_N_lpf;		
	
	U_IALDATA_TYPE	Idc_P_hpf;
	U_IALDATA_TYPE	Idc_N_hpf;
	U_IALDATA_TYPE	Ia_P_rms;
	U_IALDATA_TYPE	Ib_P_rms;
	U_IALDATA_TYPE	Ic_P_rms;		
	
	U_IALDATA_TYPE	Ia_N_rms;
	U_IALDATA_TYPE	Ib_N_rms;
	U_IALDATA_TYPE	Ic_N_rms;
	U_IALDATA_TYPE	Pdc;
	U_IALDATA_TYPE	Pac;			
	U_IALDATA_TYPE	Status;			
	// 모니터링 데이터 추가

	U_IALDATA_TYPE	uReserved[IALHMI_INTERFACE_LEN - 47];
} ST_MESCPUTX_TYPE;

typedef struct stMesCpuRxtype {
	// 기타 CPU 보드 입력 데이터 추가
	U_IALDATA_TYPE	uReserved[IALHMI_INTERFACE_LEN];
} ST_MESCPURX_TYPE;

 
#endif


